addSbtPlugin("io.spray"      % "sbt-revolver"  % "0.10.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"  % "2.5.2")
addSbtPlugin("com.eed3si9n"  % "sbt-assembly"  % "2.2.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"  % "0.12.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.11")
